#!/usr/bin/env python3
"""
Convert cv.xlsx to cv-data.js so that index.html can load CV data
without a local server (works with file:// double-click).

Run whenever cv.xlsx changes (i.e. after running generate_cv_xlsx.py):
    cd data/cv-data
    python3 make_cv_data_js.py
"""
import json, sys
from pathlib import Path

try:
    import openpyxl
except ImportError:
    sys.exit("openpyxl not found — install with:  pip3 install openpyxl")

src = Path(__file__).parent / "cv.xlsx"
dst = Path(__file__).parent / "cv-data.js"

wb = openpyxl.load_workbook(src, read_only=True, data_only=True)
ws = wb.active

rows_iter   = ws.iter_rows(values_only=True)
raw_headers = next(rows_iter)
headers     = [str(c) if c is not None else "" for c in raw_headers]

rows = []
for vals in rows_iter:
    obj = {h: (str(v) if v is not None else "") for h, v in zip(headers, vals) if h}
    rows.append(obj)

wb.close()

dst.write_text(
    "// Generated by make_cv_data_js.py — re-run this script whenever cv.xlsx changes.\n"
    "window.__TIMELINE_DATA__ = " + json.dumps(rows, ensure_ascii=False) + ";\n",
    encoding="utf-8",
)
print(f"Wrote {len(rows)} rows  →  {dst}")
